export const LENDING_STATUS = Object.freeze({
  PENDING: 'PENDING',
  BORROWER_VALIDATED: 'BORROWER_VALIDATED',
  BOOK_VALIDATED: 'BOOK_VALIDATED',
  CONFIRMED: 'CONFIRMED',
});

export const LEND_BOOK_VALIDATION_STATUS = Object.freeze({
  BOOK_VALIDATED: 'BOOK_VALIDATED',
  BOOK_NOT_VALIDATED: 'BOOK_NOT_VALIDATED',
  BORROWER_VALIDATED: 'BORROWER_VALIDATED',
  BORROWER_NOT_VALIDATED: 'BORROWER_NOT_VALIDATED',
});

export const OUTGOING_OPERATIONS = Object.freeze({
  VALIDATE_LEND_BOOK: 'VALIDATE_LEND_BOOK',
  VALIDATE_BOOK_BORROWER: 'VALIDATE_BOOK_BORROWER',
});

export const INCOMING_OPERATIONS = Object.freeze({
  VALIDATE_LEND_BOOK: 'VALIDATE_LEND_BOOK',
  VALIDATE_BOOK_BORROWER: 'VALIDATE_BOOK_BORROWER',
});
