language: node_js
node_js:
  - lts/*
notifications:
  email: false # Disable all mail notifications
services:
  - postgresql
addons:
  postgresql: '9.6'
env:
  global:
    - PGUSER=postgres
    - PGPASSWORD=
    - PGHOST=localhost
    - PGPORT=5432
    - PGDATABASE=postgres
    - PGSCHEMA=celsus_core
script:
  - npm run lint
  - npm run build:ci
after_script: npm run coverage
